/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql

import org.apache.spark.sql.catalyst.catalog.{CatalogColumnStat, CatalogStatistics}

object TPCDSTableStats {

  // These data statistics are extracted from generated TPCDS data with SF=1

  // scalastyle:off line.size.limit
  val sf1TableStats = Map(
    "customer" -> CatalogStatistics(25000000L, Some(100000L), Map(
      "c_salutation" -> CatalogColumnStat(Some(6L), None, None, Some(3410), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "c_first_name" -> CatalogColumnStat(Some(3995L), None, None, Some(3492), Some(6), Some(11), None, CatalogColumnStat.VERSION),
      "c_current_hdemo_sk" -> CatalogColumnStat(Some(7083L), Some("1"), Some("7200"), Some(3431), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "c_birth_year" -> CatalogColumnStat(Some(67L), Some("1924"), Some("1992"), Some(3453), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "c_birth_country" -> CatalogColumnStat(Some(196L), None, None, Some(3439), Some(9), Some(20), None, CatalogColumnStat.VERSION),
      "c_last_review_date" -> CatalogColumnStat(Some(357L), None, None, Some(3484), Some(7), Some(7), None, CatalogColumnStat.VERSION),
      "c_current_addr_sk" -> CatalogColumnStat(Some(40242L), Some("1"), Some("50000"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "c_last_name" -> CatalogColumnStat(Some(5241L), None, None, Some(3497), Some(7), Some(13), None, CatalogColumnStat.VERSION),
      "c_birth_month" -> CatalogColumnStat(Some(12L), Some("1"), Some("12"), Some(3449), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "c_customer_id" -> CatalogColumnStat(Some(95670L), None, None, Some(0), Some(16), Some(16), None, CatalogColumnStat.VERSION),
      "c_email_address" -> CatalogColumnStat(Some(95621L), None, None, Some(3521), Some(28), Some(46), None, CatalogColumnStat.VERSION),
      "c_first_shipto_date_sk" -> CatalogColumnStat(Some(3755L), Some("2449028"), Some("2452678"), Some(3443), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "c_birth_day" -> CatalogColumnStat(Some(32L), Some("1"), Some("31"), Some(3461), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "c_customer_sk" -> CatalogColumnStat(Some(94954L), Some("1"), Some("100000"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "c_first_sales_date_sk" -> CatalogColumnStat(Some(3758L), Some("2448998"), Some("2452648"), Some(3518), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "c_current_cdemo_sk" -> CatalogColumnStat(Some(96562L), Some("17"), Some("1920788"), Some(3438), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "c_login" -> CatalogColumnStat(Some(0L), None, None, Some(100000), Some(20), Some(20), None, CatalogColumnStat.VERSION),
      "c_preferred_cust_flag" -> CatalogColumnStat(Some(2L), None, None, Some(3426), Some(1), Some(1), None, CatalogColumnStat.VERSION)
    )),
    "store_sales" -> CatalogStatistics(426299792L, Some(2880404L), Map(
      "ss_ext_discount_amt" -> CatalogColumnStat(Some(202480L), Some("0.00"), Some("17588.25"), Some(129838), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ss_promo_sk" -> CatalogColumnStat(Some(295L), Some("1"), Some("300"), Some(129484), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ss_hdemo_sk" -> CatalogColumnStat(Some(7083L), Some("1"), Some("7200"), Some(129847), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ss_cdemo_sk" -> CatalogColumnStat(Some(221902L), Some("15"), Some("1920797"), Some(129700), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ss_coupon_amt" -> CatalogColumnStat(Some(202480L), Some("0.00"), Some("17588.25"), Some(129838), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ss_sold_date_sk" -> CatalogColumnStat(Some(1781L), Some("2450816"), Some("2452642"), Some(130093), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ss_list_price" -> CatalogColumnStat(Some(18900L), Some("1.00"), Some("200.00"), Some(130003), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ss_ticket_number" -> CatalogColumnStat(Some(251549L), Some("1"), Some("240000"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ss_ext_tax" -> CatalogColumnStat(Some(77432L), Some("0.00"), Some("1749.87"), Some(130410), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ss_net_paid_inc_tax" -> CatalogColumnStat(Some(575509L), Some("0.00"), Some("21192.87"), Some(130022), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ss_customer_sk" -> CatalogColumnStat(Some(86488L), Some("1"), Some("100000"), Some(129752), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ss_net_profit" -> CatalogColumnStat(Some(549334L), Some("-9969.53"), Some("9731.70"), Some(130267), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ss_item_sk" -> CatalogColumnStat(Some(16971L), Some("1"), Some("18000"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ss_ext_list_price" -> CatalogColumnStat(Some(560755L), Some("1.12"), Some("19984.00"), Some(129933), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ss_addr_sk" -> CatalogColumnStat(Some(45097L), Some("1"), Some("50000"), Some(129975), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ss_quantity" -> CatalogColumnStat(Some(99L), Some("1"), Some("100"), Some(129996), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ss_sales_price" -> CatalogColumnStat(Some(17521L), Some("0.00"), Some("199.56"), Some(129666), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ss_ext_sales_price" -> CatalogColumnStat(Some(396063L), Some("0.00"), Some("19562.40"), Some(130327), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ss_store_sk" -> CatalogColumnStat(Some(6L), Some("1"), Some("10"), Some(130034), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ss_net_paid" -> CatalogColumnStat(Some(435967L), Some("0.00"), Some("19562.40"), Some(129397), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ss_wholesale_cost" -> CatalogColumnStat(Some(9503L), Some("1.00"), Some("100.00"), Some(130023), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ss_sold_time_sk" -> CatalogColumnStat(Some(47033L), Some("28800"), Some("75599"), Some(129637), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ss_ext_wholesale_cost" -> CatalogColumnStat(Some(374158L), Some("1.00"), Some("10000.00"), Some(130044), Some(8), Some(8), None, CatalogColumnStat.VERSION)
    )),
    "web_sales" -> CatalogStatistics(146754336L, Some(719384L), Map(
      "ws_ext_discount_amt" -> CatalogColumnStat(Some(284456L), Some("0.00"), Some("29317.00"), Some(179), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ws_bill_cdemo_sk" -> CatalogColumnStat(Some(61768L), Some("31"), Some("1920747"), Some(165), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_ship_addr_sk" -> CatalogColumnStat(Some(33734L), Some("1"), Some("50000"), Some(178), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_ext_tax" -> CatalogColumnStat(Some(71944L), Some("0.00"), Some("2433.41"), Some(184), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ws_warehouse_sk" -> CatalogColumnStat(Some(5L), Some("1"), Some("5"), Some(179), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_net_profit" -> CatalogColumnStat(Some(319587L), Some("-9938.00"), Some("18864.56"), Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ws_net_paid_inc_tax" -> CatalogColumnStat(Some(353954L), Some("0.00"), Some("30821.43"), Some(175), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ws_quantity" -> CatalogColumnStat(Some(99L), Some("1"), Some("100"), Some(182), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_sold_time_sk" -> CatalogColumnStat(Some(37969L), Some("7"), Some("86367"), Some(187), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_ext_sales_price" -> CatalogColumnStat(Some(283014L), Some("0.00"), Some("28592.19"), Some(181), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ws_bill_customer_sk" -> CatalogColumnStat(Some(43581L), Some("2"), Some("100000"), Some(167), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_coupon_amt" -> CatalogColumnStat(Some(99070L), Some("0.00"), Some("26909.62"), Some(196), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ws_ship_customer_sk" -> CatalogColumnStat(Some(40722L), Some("2"), Some("99999"), Some(173), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_sales_price" -> CatalogColumnStat(Some(24705L), Some("0.00"), Some("299.16"), Some(167), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ws_net_paid_inc_ship" -> CatalogColumnStat(Some(357444L), Some("0.00"), Some("41222.09"), Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ws_net_paid_inc_ship_tax" -> CatalogColumnStat(Some(427058L), Some("0.00"), Some("43505.15"), Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ws_order_number" -> CatalogColumnStat(Some(56058L), Some("1"), Some("60000"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_sold_date_sk" -> CatalogColumnStat(Some(1781L), Some("2450816"), Some("2452642"), Some(189), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_bill_addr_sk" -> CatalogColumnStat(Some(34858L), Some("1"), Some("50000"), Some(172), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_web_page_sk" -> CatalogColumnStat(Some(59L), Some("1"), Some("60"), Some(188), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_ext_wholesale_cost" -> CatalogColumnStat(Some(276642L), Some("1.00"), Some("10000.00"), Some(197), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ws_ship_cdemo_sk" -> CatalogColumnStat(Some(65416L), Some("12"), Some("1920716"), Some(171), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_list_price" -> CatalogColumnStat(Some(28920L), Some("1.01"), Some("300.00"), Some(184), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ws_promo_sk" -> CatalogColumnStat(Some(295L), Some("1"), Some("300"), Some(184), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_item_sk" -> CatalogColumnStat(Some(16971L), Some("1"), Some("18000"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_ext_ship_cost" -> CatalogColumnStat(Some(208941L), Some("0.00"), Some("14231.25"), Some(198), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ws_web_site_sk" -> CatalogColumnStat(Some(31L), Some("1"), Some("30"), Some(186), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_ext_list_price" -> CatalogColumnStat(Some(383160L), Some("1.11"), Some("29424.00"), Some(180), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ws_ship_hdemo_sk" -> CatalogColumnStat(Some(7083L), Some("1"), Some("7200"), Some(165), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_bill_hdemo_sk" -> CatalogColumnStat(Some(7083L), Some("1"), Some("7200"), Some(183), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_ship_mode_sk" -> CatalogColumnStat(Some(20L), Some("1"), Some("20"), Some(174), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_wholesale_cost" -> CatalogColumnStat(Some(9503L), Some("1.00"), Some("100.00"), Some(173), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ws_ship_date_sk" -> CatalogColumnStat(Some(1898L), Some("2450817"), Some("2452762"), Some(177), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ws_net_paid" -> CatalogColumnStat(Some(276814L), Some("0.00"), Some("28538.37"), Some(169), Some(8), Some(8), None, CatalogColumnStat.VERSION)
    )),
    "date_dim" -> CatalogStatistics(19284936L, Some(73049L), Map(
      "d_current_quarter" -> CatalogColumnStat(Some(2L), None, None, Some(0), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "d_date_id" -> CatalogColumnStat(Some(73049L), None, None, Some(0), Some(16), Some(16), None, CatalogColumnStat.VERSION),
      "d_weekend" -> CatalogColumnStat(Some(2L), None, None, Some(0), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "d_same_day_lq" -> CatalogColumnStat(Some(73049L), Some("2414930"), Some("2487978"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "d_dow" -> CatalogColumnStat(Some(7L), Some("0"), Some("6"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "d_first_dom" -> CatalogColumnStat(Some(2329L), Some("2415021"), Some("2488070"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "d_following_holiday" -> CatalogColumnStat(Some(2L), None, None, Some(0), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "d_date_sk" -> CatalogColumnStat(Some(73049L), Some("2415022"), Some("2488070"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "d_fy_week_seq" -> CatalogColumnStat(Some(10010L), Some("1"), Some("10436"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "d_holiday" -> CatalogColumnStat(Some(2L), None, None, Some(0), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "d_fy_year" -> CatalogColumnStat(Some(202L), Some("1900"), Some("2100"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "d_current_day" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "d_week_seq" -> CatalogColumnStat(Some(10010L), Some("1"), Some("10436"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "d_moy" -> CatalogColumnStat(Some(12L), Some("1"), Some("12"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "d_month_seq" -> CatalogColumnStat(Some(2431L), Some("0"), Some("2400"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "d_fy_quarter_seq" -> CatalogColumnStat(Some(787L), Some("1"), Some("801"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "d_quarter_seq" -> CatalogColumnStat(Some(787L), Some("1"), Some("801"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "d_current_year" -> CatalogColumnStat(Some(2L), None, None, Some(0), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "d_dom" -> CatalogColumnStat(Some(32L), Some("1"), Some("31"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "d_last_dom" -> CatalogColumnStat(Some(2386L), Some("2415020"), Some("2488372"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "d_current_week" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "d_quarter_name" -> CatalogColumnStat(Some(774L), None, None, Some(0), Some(6), Some(6), None, CatalogColumnStat.VERSION),
      "d_qoy" -> CatalogColumnStat(Some(4L), Some("1"), Some("4"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "d_date" -> CatalogColumnStat(Some(73049L), None, None, Some(0), Some(10), Some(10), None, CatalogColumnStat.VERSION),
      "d_current_month" -> CatalogColumnStat(Some(2L), None, None, Some(0), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "d_same_day_ly" -> CatalogColumnStat(Some(73049L), Some("2414657"), Some("2487705"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "d_year" -> CatalogColumnStat(Some(202L), Some("1900"), Some("2100"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "d_day_name" -> CatalogColumnStat(Some(7L), None, None, Some(0), Some(8), Some(9), None, CatalogColumnStat.VERSION)
    )),
    "household_demographics" -> CatalogStatistics(316800L, Some(7200L), Map(
      "hd_vehicle_count" -> CatalogColumnStat(Some(6L), Some("-1"), Some("4"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "hd_buy_potential" -> CatalogColumnStat(Some(6L), None, None, Some(0), Some(8), Some(10), None, CatalogColumnStat.VERSION),
      "hd_dep_count" -> CatalogColumnStat(Some(10L), Some("0"), Some("9"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "hd_demo_sk" -> CatalogColumnStat(Some(7083L), Some("1"), Some("7200"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "hd_income_band_sk" -> CatalogColumnStat(Some(20L), Some("1"), Some("20"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION)
    )),
    "call_center" -> CatalogStatistics(3258L, Some(6L), Map(
      "cc_street_number" -> CatalogColumnStat(Some(3L), None, None, Some(0), Some(3), Some(3), None, CatalogColumnStat.VERSION),
      "cc_city" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(6), Some(6), None, CatalogColumnStat.VERSION),
      "cc_manager" -> CatalogColumnStat(Some(4L), None, None, Some(0), Some(13), Some(14), None, CatalogColumnStat.VERSION),
      "cc_open_date_sk" -> CatalogColumnStat(Some(3L), Some("2450806"), Some("2451063"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cc_division" -> CatalogColumnStat(Some(4L), Some("1"), Some("5"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cc_division_name" -> CatalogColumnStat(Some(4L), None, None, Some(0), Some(4), Some(5), None, CatalogColumnStat.VERSION),
      "cc_state" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(2), Some(2), None, CatalogColumnStat.VERSION),
      "cc_sq_ft" -> CatalogColumnStat(Some(6L), Some("649"), Some("4134"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cc_name" -> CatalogColumnStat(Some(3L), None, None, Some(0), Some(12), Some(13), None, CatalogColumnStat.VERSION),
      "cc_rec_start_date" -> CatalogColumnStat(Some(4L), Some("1998-01-01"), Some("2002-01-01"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cc_market_manager" -> CatalogColumnStat(Some(4L), None, None, Some(0), Some(13), Some(15), None, CatalogColumnStat.VERSION),
      "cc_call_center_id" -> CatalogColumnStat(Some(3L), None, None, Some(0), Some(16), Some(16), None, CatalogColumnStat.VERSION),
      "cc_gmt_offset" -> CatalogColumnStat(Some(1L), Some("-5.00"), Some("-5.00"), Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cc_tax_percentage" -> CatalogColumnStat(Some(4L), Some("0.01"), Some("0.12"), Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cc_street_name" -> CatalogColumnStat(Some(3L), None, None, Some(0), Some(10), Some(11), None, CatalogColumnStat.VERSION),
      "cc_hours" -> CatalogColumnStat(Some(2L), None, None, Some(0), Some(7), Some(7), None, CatalogColumnStat.VERSION),
      "cc_county" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(17), Some(17), None, CatalogColumnStat.VERSION),
      "cc_street_type" -> CatalogColumnStat(Some(3L), None, None, Some(0), Some(4), Some(9), None, CatalogColumnStat.VERSION),
      "cc_class" -> CatalogColumnStat(Some(3L), None, None, Some(0), Some(6), Some(6), None, CatalogColumnStat.VERSION),
      "cc_company" -> CatalogColumnStat(Some(4L), Some("1"), Some("6"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cc_rec_end_date" -> CatalogColumnStat(Some(3L), Some("2000-01-01"), Some("2001-12-31"), Some(3), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cc_country" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(13), Some(13), None, CatalogColumnStat.VERSION),
      "cc_mkt_class" -> CatalogColumnStat(Some(5L), None, None, Some(0), Some(38), Some(45), None, CatalogColumnStat.VERSION),
      "cc_mkt_desc" -> CatalogColumnStat(Some(4L), None, None, Some(0), Some(70), Some(92), None, CatalogColumnStat.VERSION),
      "cc_closed_date_sk" -> CatalogColumnStat(Some(0L), None, None, Some(6), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cc_suite_number" -> CatalogColumnStat(Some(3L), None, None, Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cc_employees" -> CatalogColumnStat(Some(5L), Some("1"), Some("7"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cc_company_name" -> CatalogColumnStat(Some(4L), None, None, Some(0), Some(4), Some(5), None, CatalogColumnStat.VERSION),
      "cc_mkt_id" -> CatalogColumnStat(Some(3L), Some("2"), Some("6"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cc_call_center_sk" -> CatalogColumnStat(Some(6L), Some("1"), Some("6"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cc_zip" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(5), Some(5), None, CatalogColumnStat.VERSION)
    )),
    "catalog_page" -> CatalogStatistics(2167830L, Some(11718L), Map(
      "cp_catalog_number" -> CatalogColumnStat(Some(110L), Some("1"), Some("109"), Some(104), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cp_catalog_page_sk" -> CatalogColumnStat(Some(11584L), Some("1"), Some("11718"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cp_catalog_page_number" -> CatalogColumnStat(Some(109L), Some("1"), Some("108"), Some(116), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cp_department" -> CatalogColumnStat(Some(1L), None, None, Some(120), Some(10), Some(10), None, CatalogColumnStat.VERSION),
      "cp_start_date_sk" -> CatalogColumnStat(Some(88L), Some("2450815"), Some("2453005"), Some(101), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cp_type" -> CatalogColumnStat(Some(3L), None, None, Some(110), Some(8), Some(9), None, CatalogColumnStat.VERSION),
      "cp_catalog_page_id" -> CatalogColumnStat(Some(11601L), None, None, Some(0), Some(16), Some(16), None, CatalogColumnStat.VERSION),
      "cp_description" -> CatalogColumnStat(Some(10619L), None, None, Some(109), Some(75), Some(99), None, CatalogColumnStat.VERSION),
      "cp_end_date_sk" -> CatalogColumnStat(Some(101L), Some("2450844"), Some("2453186"), Some(108), Some(4), Some(4), None, CatalogColumnStat.VERSION)
    )),
    "catalog_returns" -> CatalogStatistics(21898184L, Some(144067L), Map(
      "cr_item_sk" -> CatalogColumnStat(Some(16888L), Some("1"), Some("18000"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_return_tax" -> CatalogColumnStat(Some(27101L), Some("0.00"), Some("2062.43"), Some(2847), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cr_reversed_charge" -> CatalogColumnStat(Some(52939L), Some("0.00"), Some("17158.23"), Some(2842), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cr_returning_customer_sk" -> CatalogColumnStat(Some(72990L), Some("1"), Some("99999"), Some(2812), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_call_center_sk" -> CatalogColumnStat(Some(6L), Some("1"), Some("6"), Some(2851), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_refunded_customer_sk" -> CatalogColumnStat(Some(58192L), Some("2"), Some("100000"), Some(2819), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_returned_date_sk" -> CatalogColumnStat(Some(1978L), Some("2450822"), Some("2452907"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_reason_sk" -> CatalogColumnStat(Some(35L), Some("1"), Some("35"), Some(2840), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_returned_time_sk" -> CatalogColumnStat(Some(65553L), Some("2"), Some("86399"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_return_amount" -> CatalogColumnStat(Some(81669L), Some("0.00"), Some("24445.40"), Some(2876), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cr_returning_hdemo_sk" -> CatalogColumnStat(Some(7083L), Some("1"), Some("7200"), Some(2882), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_refunded_addr_sk" -> CatalogColumnStat(Some(39198L), Some("1"), Some("50000"), Some(2849), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_refunded_cash" -> CatalogColumnStat(Some(72766L), Some("0.00"), Some("22110.68"), Some(2849), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cr_order_number" -> CatalogColumnStat(Some(89778L), Some("2"), Some("160000"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_catalog_page_sk" -> CatalogColumnStat(Some(6438L), Some("1"), Some("9828"), Some(2877), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_ship_mode_sk" -> CatalogColumnStat(Some(20L), Some("1"), Some("20"), Some(2807), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_return_ship_cost" -> CatalogColumnStat(Some(63981L), Some("0.00"), Some("11890.06"), Some(2805), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cr_store_credit" -> CatalogColumnStat(Some(49427L), Some("0.00"), Some("16255.33"), Some(2846), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cr_refunded_hdemo_sk" -> CatalogColumnStat(Some(7083L), Some("1"), Some("7200"), Some(2874), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_net_loss" -> CatalogColumnStat(Some(84643L), Some("1.01"), Some("13213.89"), Some(2902), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cr_return_amt_inc_tax" -> CatalogColumnStat(Some(94386L), Some("0.00"), Some("25403.76"), Some(2902), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cr_returning_cdemo_sk" -> CatalogColumnStat(Some(141209L), Some("13"), Some("1920792"), Some(2858), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_returning_addr_sk" -> CatalogColumnStat(Some(43435L), Some("1"), Some("50000"), Some(2844), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_refunded_cdemo_sk" -> CatalogColumnStat(Some(91048L), Some("5"), Some("1920733"), Some(2819), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_fee" -> CatalogColumnStat(Some(9571L), Some("0.50"), Some("100.00"), Some(2873), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cr_warehouse_sk" -> CatalogColumnStat(Some(5L), Some("1"), Some("5"), Some(2935), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cr_return_quantity" -> CatalogColumnStat(Some(99L), Some("1"), Some("100"), Some(2895), Some(4), Some(4), None, CatalogColumnStat.VERSION)
    )),
    "catalog_sales" -> CatalogStatistics(294075792L, Some(1441548L), Map(
      "cs_sales_price" -> CatalogColumnStat(Some(25167L), Some("0.00"), Some("297.83"), Some(7015), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cs_ship_date_sk" -> CatalogColumnStat(Some(1886L), Some("2450817"), Some("2452738"), Some(7147), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_order_number" -> CatalogColumnStat(Some(157418L), Some("1"), Some("160000"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_bill_addr_sk" -> CatalogColumnStat(Some(43897L), Some("1"), Some("50000"), Some(7101), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_ship_addr_sk" -> CatalogColumnStat(Some(44422L), Some("1"), Some("50000"), Some(7165), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_ship_mode_sk" -> CatalogColumnStat(Some(20L), Some("1"), Some("20"), Some(7127), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_ext_list_price" -> CatalogColumnStat(Some(572069L), Some("1.29"), Some("29976.00"), Some(7051), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cs_net_paid_inc_tax" -> CatalogColumnStat(Some(538598L), Some("0.00"), Some("30261.56"), Some(7127), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cs_ship_customer_sk" -> CatalogColumnStat(Some(76631L), Some("1"), Some("100000"), Some(7226), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_sold_time_sk" -> CatalogColumnStat(Some(66107L), Some("4"), Some("86399"), Some(7053), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_promo_sk" -> CatalogColumnStat(Some(295L), Some("1"), Some("300"), Some(7234), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_net_profit" -> CatalogColumnStat(Some(516604L), Some("-9897.03"), Some("18950.00"), Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cs_ext_discount_amt" -> CatalogColumnStat(Some(392776L), Some("0.00"), Some("28300.44"), Some(7154), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cs_ext_ship_cost" -> CatalogColumnStat(Some(268195L), Some("0.00"), Some("14416.00"), Some(7245), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cs_catalog_page_sk" -> CatalogColumnStat(Some(6456L), Some("1"), Some("9828"), Some(7170), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_net_paid" -> CatalogColumnStat(Some(412393L), Some("0.00"), Some("28767.00"), Some(7150), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cs_ext_tax" -> CatalogColumnStat(Some(84430L), Some("0.00"), Some("2416.94"), Some(7135), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cs_wholesale_cost" -> CatalogColumnStat(Some(9503L), Some("1.00"), Some("100.00"), Some(7136), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cs_bill_customer_sk" -> CatalogColumnStat(Some(75408L), Some("1"), Some("100000"), Some(7029), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_net_paid_inc_ship_tax" -> CatalogColumnStat(Some(652197L), Some("0.00"), Some("43335.20"), Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cs_bill_cdemo_sk" -> CatalogColumnStat(Some(151551L), Some("5"), Some("1920765"), Some(7150), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_ext_sales_price" -> CatalogColumnStat(Some(401906L), Some("0.00"), Some("28846.00"), Some(7208), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cs_sold_date_sk" -> CatalogColumnStat(Some(1772L), Some("2450815"), Some("2452648"), Some(7180), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_item_sk" -> CatalogColumnStat(Some(16971L), Some("1"), Some("18000"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_ship_cdemo_sk" -> CatalogColumnStat(Some(157749L), Some("5"), Some("1920765"), Some(7137), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_quantity" -> CatalogColumnStat(Some(99L), Some("1"), Some("100"), Some(7091), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_bill_hdemo_sk" -> CatalogColumnStat(Some(7083L), Some("1"), Some("7200"), Some(7060), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_call_center_sk" -> CatalogColumnStat(Some(6L), Some("1"), Some("6"), Some(7120), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_coupon_amt" -> CatalogColumnStat(Some(164884L), Some("0.00"), Some("24188.55"), Some(7185), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cs_ext_wholesale_cost" -> CatalogColumnStat(Some(330013L), Some("1.02"), Some("9999.00"), Some(7167), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cs_warehouse_sk" -> CatalogColumnStat(Some(5L), Some("1"), Some("5"), Some(7146), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cs_net_paid_inc_ship" -> CatalogColumnStat(Some(521584L), Some("0.00"), Some("41371.47"), Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cs_list_price" -> CatalogColumnStat(Some(29429L), Some("1.01"), Some("300.00"), Some(7213), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "cs_ship_hdemo_sk" -> CatalogColumnStat(Some(7083L), Some("1"), Some("7200"), Some(7133), Some(4), Some(4), None, CatalogColumnStat.VERSION)
    )),
    "customer_address" -> CatalogStatistics(12250000L, Some(50000L), Map(
      "ca_location_type" -> CatalogColumnStat(Some(3L), None, None, Some(1492), Some(9), Some(13), None, CatalogColumnStat.VERSION),
      "ca_county" -> CatalogColumnStat(Some(1957L), None, None, Some(1464), Some(14), Some(28), None, CatalogColumnStat.VERSION),
      "ca_city" -> CatalogColumnStat(Some(694L), None, None, Some(1519), Some(9), Some(20), None, CatalogColumnStat.VERSION),
      "ca_street_number" -> CatalogColumnStat(Some(1034L), None, None, Some(1532), Some(3), Some(4), None, CatalogColumnStat.VERSION),
      "ca_state" -> CatalogColumnStat(Some(54L), None, None, Some(1550), Some(2), Some(2), None, CatalogColumnStat.VERSION),
      "ca_street_name" -> CatalogColumnStat(Some(6645L), None, None, Some(1479), Some(9), Some(21), None, CatalogColumnStat.VERSION),
      "ca_gmt_offset" -> CatalogColumnStat(Some(6L), Some("-10.00"), Some("-5.00"), Some(1556), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "ca_address_sk" -> CatalogColumnStat(Some(45888L), Some("1"), Some("50000"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ca_street_type" -> CatalogColumnStat(Some(20L), None, None, Some(1501), Some(5), Some(9), None, CatalogColumnStat.VERSION),
      "ca_country" -> CatalogColumnStat(Some(1L), None, None, Some(1525), Some(13), Some(13), None, CatalogColumnStat.VERSION),
      "ca_suite_number" -> CatalogColumnStat(Some(76L), None, None, Some(1485), Some(8), Some(9), None, CatalogColumnStat.VERSION),
      "ca_address_id" -> CatalogColumnStat(Some(47943L), None, None, Some(0), Some(16), Some(16), None, CatalogColumnStat.VERSION),
      "ca_zip" -> CatalogColumnStat(Some(3868L), None, None, Some(1539), Some(5), Some(5), None, CatalogColumnStat.VERSION)
    )),
    "customer_demographics" -> CatalogStatistics(182476000L, Some(1920800L), Map(
      "cd_education_status" -> CatalogColumnStat(Some(7L), None, None, Some(0), Some(10), Some(15), None, CatalogColumnStat.VERSION),
      "cd_dep_college_count" -> CatalogColumnStat(Some(7L), Some("0"), Some("6"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cd_marital_status" -> CatalogColumnStat(Some(5L), None, None, Some(0), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "cd_dep_count" -> CatalogColumnStat(Some(7L), Some("0"), Some("6"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cd_credit_rating" -> CatalogColumnStat(Some(4L), None, None, Some(0), Some(7), Some(9), None, CatalogColumnStat.VERSION),
      "cd_gender" -> CatalogColumnStat(Some(2L), None, None, Some(0), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "cd_dep_employed_count" -> CatalogColumnStat(Some(7L), Some("0"), Some("6"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cd_purchase_estimate" -> CatalogColumnStat(Some(20L), Some("500"), Some("10000"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "cd_demo_sk" -> CatalogColumnStat(Some(1847065L), Some("1"), Some("1920800"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION)
    )),
    "income_band" -> CatalogStatistics(400L, Some(20L), Map(
      "ib_income_band_sk" -> CatalogColumnStat(Some(20L), Some("1"), Some("20"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ib_lower_bound" -> CatalogColumnStat(Some(19L), Some("0"), Some("190001"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "ib_upper_bound" -> CatalogColumnStat(Some(20L), Some("10000"), Some("200000"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION)
    )),
    "inventory" -> CatalogStatistics(281880000L, Some(11745000L), Map(
      "inv_date_sk" -> CatalogColumnStat(Some(267L), Some("2450815"), Some("2452635"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "inv_item_sk" -> CatalogColumnStat(Some(16971L), Some("1"), Some("18000"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "inv_warehouse_sk" -> CatalogColumnStat(Some(5L), Some("1"), Some("5"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "inv_quantity_on_hand" -> CatalogColumnStat(Some(1026L), Some("0"), Some("1000"), Some(586913), Some(4), Some(4), None, CatalogColumnStat.VERSION)
    )),
    "item" -> CatalogStatistics(8244000L, Some(18000L), Map(
      "i_manufact_id" -> CatalogColumnStat(Some(1012L), Some("1"), Some("1000"), Some(38), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "i_brand" -> CatalogColumnStat(Some(671L), None, None, Some(40), Some(17), Some(22), None, CatalogColumnStat.VERSION),
      "i_category" -> CatalogColumnStat(Some(10L), None, None, Some(43), Some(6), Some(11), None, CatalogColumnStat.VERSION),
      "i_container" -> CatalogColumnStat(Some(1L), None, None, Some(39), Some(7), Some(7), None, CatalogColumnStat.VERSION),
      "i_item_desc" -> CatalogColumnStat(Some(13473L), None, None, Some(51), Some(101), Some(200), None, CatalogColumnStat.VERSION),
      "i_manufact" -> CatalogColumnStat(Some(983L), None, None, Some(43), Some(12), Some(15), None, CatalogColumnStat.VERSION),
      "i_rec_end_date" -> CatalogColumnStat(Some(3L), None, None, Some(9000), Some(10), Some(10), None, CatalogColumnStat.VERSION),
      "i_color" -> CatalogColumnStat(Some(88L), None, None, Some(45), Some(6), Some(10), None, CatalogColumnStat.VERSION),
      "i_units" -> CatalogColumnStat(Some(21L), None, None, Some(43), Some(5), Some(7), None, CatalogColumnStat.VERSION),
      "i_class_id" -> CatalogColumnStat(Some(16L), Some("1"), Some("16"), Some(35), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "i_product_name" -> CatalogColumnStat(Some(17964L), None, None, Some(36), Some(19), Some(25), None, CatalogColumnStat.VERSION),
      "i_class" -> CatalogColumnStat(Some(100L), None, None, Some(43), Some(8), Some(15), None, CatalogColumnStat.VERSION),
      "i_wholesale_cost" -> CatalogColumnStat(Some(2018L), Some("0.02"), Some("87.36"), Some(46), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "i_formulation" -> CatalogColumnStat(Some(13169L), None, None, Some(43), Some(20), Some(20), None, CatalogColumnStat.VERSION),
      "i_rec_start_date" -> CatalogColumnStat(Some(4L), None, None, Some(46), Some(10), Some(10), None, CatalogColumnStat.VERSION),
      "i_item_id" -> CatalogColumnStat(Some(10293L), None, None, Some(0), Some(16), Some(16), None, CatalogColumnStat.VERSION),
      "i_current_price" -> CatalogColumnStat(Some(2734L), Some("0.09"), Some("99.99"), Some(45), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "i_category_id" -> CatalogColumnStat(Some(10L), Some("1"), Some("10"), Some(42), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "i_brand_id" -> CatalogColumnStat(Some(857L), Some("1001001"), Some("10016017"), Some(44), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "i_item_sk" -> CatalogColumnStat(Some(16971L), Some("1"), Some("18000"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "i_size" -> CatalogColumnStat(Some(7L), None, None, Some(41), Some(5), Some(11), None, CatalogColumnStat.VERSION),
      "i_manager_id" -> CatalogColumnStat(Some(99L), Some("1"), Some("100"), Some(41), Some(4), Some(4), None, CatalogColumnStat.VERSION)
    )),
    "promotion" -> CatalogStatistics(80700L, Some(300L), Map(
      "p_promo_id" -> CatalogColumnStat(Some(300L), None, None, Some(0), Some(16), Some(16), None, CatalogColumnStat.VERSION),
      "p_promo_sk" -> CatalogColumnStat(Some(295L), Some("1"), Some("300"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "p_response_target" -> CatalogColumnStat(Some(1L), Some("1"), Some("1"), Some(7), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "p_discount_active" -> CatalogColumnStat(Some(1L), None, None, Some(7), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "p_channel_demo" -> CatalogColumnStat(Some(1L), None, None, Some(3), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "p_promo_name" -> CatalogColumnStat(Some(10L), None, None, Some(7), Some(4), Some(5), None, CatalogColumnStat.VERSION),
      "p_start_date_sk" -> CatalogColumnStat(Some(245L), Some("2450100"), Some("2450913"), Some(6), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "p_channel_catalog" -> CatalogColumnStat(Some(1L), None, None, Some(4), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "p_channel_radio" -> CatalogColumnStat(Some(1L), None, None, Some(6), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "p_cost" -> CatalogColumnStat(Some(1L), Some("1000.00"), Some("1000.00"), Some(6), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "p_channel_details" -> CatalogColumnStat(Some(298L), None, None, Some(2), Some(41), Some(60), None, CatalogColumnStat.VERSION),
      "p_channel_email" -> CatalogColumnStat(Some(1L), None, None, Some(5), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "p_channel_tv" -> CatalogColumnStat(Some(1L), None, None, Some(6), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "p_channel_press" -> CatalogColumnStat(Some(1L), None, None, Some(7), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "p_item_sk" -> CatalogColumnStat(Some(288L), Some("28"), Some("17926"), Some(7), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "p_purpose" -> CatalogColumnStat(Some(1L), None, None, Some(4), Some(7), Some(7), None, CatalogColumnStat.VERSION),
      "p_channel_event" -> CatalogColumnStat(Some(1L), None, None, Some(4), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "p_channel_dmail" -> CatalogColumnStat(Some(2L), None, None, Some(5), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "p_end_date_sk" -> CatalogColumnStat(Some(264L), Some("2450132"), Some("2450955"), Some(6), Some(4), Some(4), None, CatalogColumnStat.VERSION)
    )),
    "reason" -> CatalogStatistics(2415L, Some(35L), Map(
      "r_reason_sk" -> CatalogColumnStat(Some(35L), Some("1"), Some("35"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "r_reason_id" -> CatalogColumnStat(Some(35L), None, None, Some(0), Some(16), Some(16), None, CatalogColumnStat.VERSION),
      "r_reason_desc" -> CatalogColumnStat(Some(34L), None, None, Some(0), Some(17), Some(43), None, CatalogColumnStat.VERSION)
    )),
    "ship_mode" -> CatalogStatistics(2420L, Some(20L), Map(
      "sm_carrier" -> CatalogColumnStat(Some(19L), None, None, Some(0), Some(7), Some(14), None, CatalogColumnStat.VERSION),
      "sm_code" -> CatalogColumnStat(Some(4L), None, None, Some(0), Some(5), Some(7), None, CatalogColumnStat.VERSION),
      "sm_type" -> CatalogColumnStat(Some(5L), None, None, Some(0), Some(8), Some(9), None, CatalogColumnStat.VERSION),
      "sm_ship_mode_id" -> CatalogColumnStat(Some(20L), None, None, Some(0), Some(16), Some(16), None, CatalogColumnStat.VERSION),
      "sm_contract" -> CatalogColumnStat(Some(18L), None, None, Some(0), Some(13), Some(20), None, CatalogColumnStat.VERSION),
      "sm_ship_mode_sk" -> CatalogColumnStat(Some(20L), Some("1"), Some("20"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION)
    )),
    "store" -> CatalogStatistics(6144L, Some(12L), Map(
      "s_country" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(13), Some(13), None, CatalogColumnStat.VERSION),
      "s_market_manager" -> CatalogColumnStat(Some(7L), None, None, Some(0), Some(14), Some(16), None, CatalogColumnStat.VERSION),
      "s_state" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(2), Some(2), None, CatalogColumnStat.VERSION),
      "s_closed_date_sk" -> CatalogColumnStat(Some(3L), Some("2450910"), Some("2451189"), Some(9), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "s_manager" -> CatalogColumnStat(Some(7L), None, None, Some(0), Some(12), Some(15), None, CatalogColumnStat.VERSION),
      "s_store_name" -> CatalogColumnStat(Some(8L), None, None, Some(0), Some(5), Some(5), None, CatalogColumnStat.VERSION),
      "s_street_type" -> CatalogColumnStat(Some(8L), None, None, Some(0), Some(5), Some(9), None, CatalogColumnStat.VERSION),
      "s_company_name" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(7), Some(7), None, CatalogColumnStat.VERSION),
      "s_gmt_offset" -> CatalogColumnStat(Some(1L), Some("-5.00"), Some("-5.00"), Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "s_rec_end_date" -> CatalogColumnStat(Some(3L), None, None, Some(6), Some(10), Some(10), None, CatalogColumnStat.VERSION),
      "s_hours" -> CatalogColumnStat(Some(2L), None, None, Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "s_county" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(17), Some(17), None, CatalogColumnStat.VERSION),
      "s_market_id" -> CatalogColumnStat(Some(7L), Some("2"), Some("10"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "s_division_id" -> CatalogColumnStat(Some(1L), Some("1"), Some("1"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "s_street_name" -> CatalogColumnStat(Some(11L), None, None, Some(0), Some(7), Some(11), None, CatalogColumnStat.VERSION),
      "s_rec_start_date" -> CatalogColumnStat(Some(4L), None, None, Some(0), Some(10), Some(10), None, CatalogColumnStat.VERSION),
      "s_city" -> CatalogColumnStat(Some(2L), None, None, Some(0), Some(7), Some(8), None, CatalogColumnStat.VERSION),
      "s_floor_space" -> CatalogColumnStat(Some(9L), Some("5219562"), Some("9341467"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "s_tax_precentage" -> CatalogColumnStat(Some(5L), Some("0.01"), Some("0.11"), Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "s_geography_class" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(7), Some(7), None, CatalogColumnStat.VERSION),
      "s_store_sk" -> CatalogColumnStat(Some(12L), Some("1"), Some("12"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "s_division_name" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(7), Some(7), None, CatalogColumnStat.VERSION),
      "s_street_number" -> CatalogColumnStat(Some(9L), None, None, Some(0), Some(3), Some(3), None, CatalogColumnStat.VERSION),
      "s_number_employees" -> CatalogColumnStat(Some(9L), Some("218"), Some("297"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "s_zip" -> CatalogColumnStat(Some(2L), None, None, Some(0), Some(5), Some(5), None, CatalogColumnStat.VERSION),
      "s_suite_number" -> CatalogColumnStat(Some(11L), None, None, Some(0), Some(9), Some(9), None, CatalogColumnStat.VERSION),
      "s_company_id" -> CatalogColumnStat(Some(1L), Some("1"), Some("1"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "s_market_desc" -> CatalogColumnStat(Some(10L), None, None, Some(0), Some(56), Some(94), None, CatalogColumnStat.VERSION),
      "s_store_id" -> CatalogColumnStat(Some(6L), None, None, Some(0), Some(16), Some(16), None, CatalogColumnStat.VERSION)
    )),
    "store_returns" -> CatalogStatistics(48302352L, Some(287514L), Map(
      "sr_return_ship_cost" -> CatalogColumnStat(Some(80881L), Some("0.00"), Some("8631.06"), Some(9871), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_net_loss" -> CatalogColumnStat(Some(123280L), Some("0.51"), Some("9256.12"), Some(9973), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_cdemo_sk" -> CatalogColumnStat(Some(240643L), Some("2"), Some("1920800"), Some(9883), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_return_amt" -> CatalogColumnStat(Some(106759L), Some("0.00"), Some("16917.12"), Some(10028), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_returned_date_sk" -> CatalogColumnStat(Some(2010L), Some("2450820"), Some("2452822"), Some(10012), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_fee" -> CatalogColumnStat(Some(9571L), Some("0.50"), Some("100.00"), Some(10065), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_return_time_sk" -> CatalogColumnStat(Some(31932L), Some("28799"), Some("61199"), Some(9946), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_return_quantity" -> CatalogColumnStat(Some(103L), Some("1"), Some("100"), Some(10063), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_hdemo_sk" -> CatalogColumnStat(Some(6609L), Some("1"), Some("7200"), Some(10121), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_refunded_cash" -> CatalogColumnStat(Some(102918L), Some("0.00"), Some("14887.06"), Some(10040), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_reversed_charge" -> CatalogColumnStat(Some(73550L), Some("0.00"), Some("11531.04"), Some(10032), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_item_sk" -> CatalogColumnStat(Some(17137L), Some("1"), Some("18000"), Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_return_amt_inc_tax" -> CatalogColumnStat(Some(144603L), Some("0.00"), Some("17593.80"), Some(9950), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_reason_sk" -> CatalogColumnStat(Some(35L), Some("1"), Some("35"), Some(9984), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_addr_sk" -> CatalogColumnStat(Some(49624L), Some("1"), Some("50000"), Some(10193), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_ticket_number" -> CatalogColumnStat(Some(161534L), Some("1"), Some("240000"), Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_return_tax" -> CatalogColumnStat(Some(29360L), Some("0.00"), Some("1253.26"), Some(10177), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_customer_sk" -> CatalogColumnStat(Some(85799L), Some("1"), Some("100000"), Some(10016), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_store_credit" -> CatalogColumnStat(Some(71343L), Some("0.00"), Some("11358.57"), Some(10098), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "sr_store_sk" -> CatalogColumnStat(Some(6L), Some("1"), Some("10"), Some(10062), Some(8), Some(8), None, CatalogColumnStat.VERSION)
    )),
    "time_dim" -> CatalogStatistics(10886400L, Some(86400L), Map(
      "t_shift" -> CatalogColumnStat(Some(3L), None, None, Some(0), Some(6), Some(6), None, CatalogColumnStat.VERSION),
      "t_time" -> CatalogColumnStat(Some(83505L), Some("0"), Some("86399"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "t_second" -> CatalogColumnStat(Some(60L), Some("0"), Some("59"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "t_sub_shift" -> CatalogColumnStat(Some(4L), None, None, Some(0), Some(7), Some(9), None, CatalogColumnStat.VERSION),
      "t_am_pm" -> CatalogColumnStat(Some(2L), None, None, Some(0), Some(2), Some(2), None, CatalogColumnStat.VERSION),
      "t_time_id" -> CatalogColumnStat(Some(80197L), None, None, Some(0), Some(16), Some(16), None, CatalogColumnStat.VERSION),
      "t_minute" -> CatalogColumnStat(Some(60L), Some("0"), Some("59"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "t_meal_time" -> CatalogColumnStat(Some(3L), None, None, Some(50400), Some(7), Some(9), None, CatalogColumnStat.VERSION),
      "t_time_sk" -> CatalogColumnStat(Some(83505L), Some("0"), Some("86399"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "t_hour" -> CatalogColumnStat(Some(25L), Some("0"), Some("23"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION)
    )),
    "warehouse" -> CatalogStatistics(1305L, Some(5L), Map(
      "w_warehouse_id" -> CatalogColumnStat(Some(5L), None, None, Some(0), Some(16), Some(16), None, CatalogColumnStat.VERSION),
      "w_street_number" -> CatalogColumnStat(Some(4L), None, None, Some(1), Some(3), Some(3), None, CatalogColumnStat.VERSION),
      "w_city" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "w_warehouse_sk" -> CatalogColumnStat(Some(5L), Some("1"), Some("5"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "w_street_name" -> CatalogColumnStat(Some(4L), None, None, Some(1), Some(9), Some(10), None, CatalogColumnStat.VERSION),
      "w_county" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(17), Some(17), None, CatalogColumnStat.VERSION),
      "w_gmt_offset" -> CatalogColumnStat(Some(1L), Some("-5.00"), Some("-5.00"), Some(1), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "w_street_type" -> CatalogColumnStat(Some(4L), None, None, Some(1), Some(6), Some(7), None, CatalogColumnStat.VERSION),
      "w_warehouse_sq_ft" -> CatalogColumnStat(Some(4L), Some("138504"), Some("977787"), Some(1), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "w_country" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(13), Some(13), None, CatalogColumnStat.VERSION),
      "w_state" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(2), Some(2), None, CatalogColumnStat.VERSION),
      "w_suite_number" -> CatalogColumnStat(Some(4L), None, None, Some(1), Some(8), Some(9), None, CatalogColumnStat.VERSION),
      "w_warehouse_name" -> CatalogColumnStat(Some(4L), None, None, Some(1), Some(18), Some(20), None, CatalogColumnStat.VERSION),
      "w_zip" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(5), Some(5), None, CatalogColumnStat.VERSION)
    )),
    "web_page" -> CatalogStatistics(8280L, Some(60L), Map(
      "wp_url" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(18), Some(18), None, CatalogColumnStat.VERSION),
      "wp_image_count" -> CatalogColumnStat(Some(7L), Some("1"), Some("7"), Some(1), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "wp_autogen_flag" -> CatalogColumnStat(Some(2L), None, None, Some(0), Some(1), Some(1), None, CatalogColumnStat.VERSION),
      "wp_web_page_id" -> CatalogColumnStat(Some(30L), None, None, Some(0), Some(16), Some(16), None, CatalogColumnStat.VERSION),
      "wp_max_ad_count" -> CatalogColumnStat(Some(5L), Some("0"), Some("4"), Some(1), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "wp_creation_date_sk" -> CatalogColumnStat(Some(9L), Some("2450807"), Some("2450815"), Some(1), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "wp_type" -> CatalogColumnStat(Some(7L), None, None, Some(1), Some(7), Some(9), None, CatalogColumnStat.VERSION),
      "wp_web_page_sk" -> CatalogColumnStat(Some(59L), Some("1"), Some("60"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "wp_access_date_sk" -> CatalogColumnStat(Some(38L), Some("2452549"), Some("2452648"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "wp_char_count" -> CatalogColumnStat(Some(38L), Some("701"), Some("7046"), Some(1), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "wp_rec_end_date" -> CatalogColumnStat(Some(3L), Some("1999-09-03"), Some("2001-09-02"), Some(30), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "wp_link_count" -> CatalogColumnStat(Some(21L), Some("2"), Some("25"), Some(1), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "wp_customer_sk" -> CatalogColumnStat(Some(17L), Some("1898"), Some("98633"), Some(39), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "wp_rec_start_date" -> CatalogColumnStat(Some(4L), Some("1997-09-03"), Some("2001-09-03"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION)
    )),
    "web_returns" -> CatalogStatistics(14352600L, Some(71763L), Map(
      "wr_reason_sk" -> CatalogColumnStat(Some(35L), Some("1"), Some("35"), Some(3212), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_returning_hdemo_sk" -> CatalogColumnStat(Some(6609L), Some("1"), Some("7200"), Some(3205), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_refunded_customer_sk" -> CatalogColumnStat(Some(49669L), Some("1"), Some("100000"), Some(3217), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_account_credit" -> CatalogColumnStat(Some(34231L), Some("0.00"), Some("13995.91"), Some(3151), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_refunded_hdemo_sk" -> CatalogColumnStat(Some(6609L), Some("1"), Some("7200"), Some(3270), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_returning_addr_sk" -> CatalogColumnStat(Some(36201L), Some("2"), Some("50000"), Some(3218), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_return_tax" -> CatalogColumnStat(Some(18115L), Some("0.00"), Some("2090.05"), Some(3257), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_order_number" -> CatalogColumnStat(Some(42632L), Some("1"), Some("59997"), Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_return_amt_inc_tax" -> CatalogColumnStat(Some(58197L), Some("0.00"), Some("26675.37"), Some(3193), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_returned_date_sk" -> CatalogColumnStat(Some(2118L), Some("2450842"), Some("2452995"), Some(3127), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_returning_cdemo_sk" -> CatalogColumnStat(Some(62104L), Some("44"), Some("1920789"), Some(3215), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_refunded_cdemo_sk" -> CatalogColumnStat(Some(62184L), Some("44"), Some("1920789"), Some(3230), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_reversed_charge" -> CatalogColumnStat(Some(34721L), Some("0.00"), Some("16140.11"), Some(3210), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_return_quantity" -> CatalogColumnStat(Some(103L), Some("1"), Some("100"), Some(3147), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_returned_time_sk" -> CatalogColumnStat(Some(44263L), Some("0"), Some("86399"), Some(3194), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_fee" -> CatalogColumnStat(Some(9571L), Some("0.50"), Some("100.00"), Some(3165), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_returning_customer_sk" -> CatalogColumnStat(Some(48927L), Some("1"), Some("100000"), Some(3138), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_refunded_cash" -> CatalogColumnStat(Some(42362L), Some("0.00"), Some("20822.97"), Some(3181), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_return_amt" -> CatalogColumnStat(Some(47854L), Some("0.00"), Some("25649.40"), Some(3211), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_return_ship_cost" -> CatalogColumnStat(Some(38441L), Some("0.00"), Some("11730.85"), Some(3187), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_item_sk" -> CatalogColumnStat(Some(16398L), Some("1"), Some("18000"), Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_net_loss" -> CatalogColumnStat(Some(52804L), Some("0.63"), Some("13871.85"), Some(3201), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_refunded_addr_sk" -> CatalogColumnStat(Some(36114L), Some("2"), Some("50000"), Some(3164), Some(8), Some(8), None, CatalogColumnStat.VERSION),
      "wr_web_page_sk" -> CatalogColumnStat(Some(62L), Some("1"), Some("60"), Some(3130), Some(8), Some(8), None, CatalogColumnStat.VERSION)
    )),
    "web_site" -> CatalogStatistics(14820L, Some(30L), Map(
      "web_company_id" -> CatalogColumnStat(Some(6L), Some("1"), Some("6"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "web_suite_number" -> CatalogColumnStat(Some(24L), None, None, Some(0), Some(9), Some(9), None, CatalogColumnStat.VERSION),
      "web_rec_end_date" -> CatalogColumnStat(Some(3L), Some("1999-08-16"), Some("2001-08-15"), Some(15), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "web_zip" -> CatalogColumnStat(Some(2L), None, None, Some(0), Some(5), Some(5), None, CatalogColumnStat.VERSION),
      "web_mkt_desc" -> CatalogColumnStat(Some(18L), None, None, Some(0), Some(69), Some(94), None, CatalogColumnStat.VERSION),
      "web_class" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(7), Some(7), None, CatalogColumnStat.VERSION),
      "web_country" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(13), Some(13), None, CatalogColumnStat.VERSION),
      "web_rec_start_date" -> CatalogColumnStat(Some(4L), Some("1997-08-16"), Some("2001-08-16"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "web_market_manager" -> CatalogColumnStat(Some(26L), None, None, Some(0), Some(13), Some(16), None, CatalogColumnStat.VERSION),
      "web_street_type" -> CatalogColumnStat(Some(15L), None, None, Some(0), Some(5), Some(9), None, CatalogColumnStat.VERSION),
      "web_name" -> CatalogColumnStat(Some(5L), None, None, Some(0), Some(6), Some(6), None, CatalogColumnStat.VERSION),
      "web_manager" -> CatalogColumnStat(Some(22L), None, None, Some(0), Some(13), Some(16), None, CatalogColumnStat.VERSION),
      "web_site_id" -> CatalogColumnStat(Some(14L), None, None, Some(0), Some(16), Some(16), None, CatalogColumnStat.VERSION),
      "web_street_number" -> CatalogColumnStat(Some(18L), None, None, Some(0), Some(3), Some(3), None, CatalogColumnStat.VERSION),
      "web_street_name" -> CatalogColumnStat(Some(30L), None, None, Some(0), Some(10), Some(14), None, CatalogColumnStat.VERSION),
      "web_open_date_sk" -> CatalogColumnStat(Some(15L), Some("2450577"), Some("2450807"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "web_county" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(17), Some(17), None, CatalogColumnStat.VERSION),
      "web_mkt_id" -> CatalogColumnStat(Some(6L), Some("1"), Some("6"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "web_gmt_offset" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(2), Some(2), None, CatalogColumnStat.VERSION),
      "web_city" -> CatalogColumnStat(Some(2L), None, None, Some(0), Some(7), Some(8), None, CatalogColumnStat.VERSION),
      "web_company_name" -> CatalogColumnStat(Some(6L), None, None, Some(0), Some(4), Some(5), None, CatalogColumnStat.VERSION),
      "web_site_sk" -> CatalogColumnStat(Some(30L), Some("1"), Some("30"), Some(0), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "web_mkt_class" -> CatalogColumnStat(Some(21L), None, None, Some(0), Some(33), Some(49), None, CatalogColumnStat.VERSION),
      "web_state" -> CatalogColumnStat(Some(1L), None, None, Some(0), Some(2), Some(2), None, CatalogColumnStat.VERSION),
      "web_close_date_sk" -> CatalogColumnStat(Some(10L), Some("2446944"), Some("2448956"), Some(5), Some(4), Some(4), None, CatalogColumnStat.VERSION),
      "web_tax_percentage" -> CatalogColumnStat(Some(10L), Some("0.00"), Some("0.12"), Some(0), Some(8), Some(8), None, CatalogColumnStat.VERSION)
    ))
  )
  // scalastyle:on line.size.limit
}
