CREATE TABLE INPUT4(KEY STRING, VALUE STRING) STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '../data/files/kv1.txt' INTO TABLE INPUT4;

EXPLAIN
SELECT a.KEY2
FROM (SELECT INPUT4.*, INPUT4.KEY as KEY2
      FROM INPUT4) a
ORDER BY KEY2 LIMIT 10;

SELECT a.KEY2
FROM (SELECT INPUT4.*, INPUT4.KEY as KEY2
      FROM INPUT4) a
ORDER BY KEY2 LIMIT 10;


