explain 
select E() FROM src LIMIT 1;

select E() FROM src LIMIT 1;

DESCRIBE FUNCTION E;
DESCRIBE FUNCTION EXTENDED E;
explain 
select E() FROM src LIMIT 1;

select E() FROM src LIMIT 1;

DESCRIBE FUNCTION E;
DESCRIBE FUNCTION EXTENDED E;
