-- Conversion of main primitive types to Float type: 
SELECT CAST(NULL AS FLOAT) FROM src LIMIT 1;

SELECT CAST(TRUE AS FLOAT) FROM src LIMIT 1;

SELECT CAST(CAST(-7 AS TINYINT) AS FLOAT) FROM src LIMIT 1;
SELECT CAST(CAST(-18 AS SMALLINT) AS FLOAT) FROM src LIMIT 1;
SELECT CAST(-129 AS FLOAT) FROM src LIMIT 1;
SELECT CAST(CAST(-1025 AS BIGINT) AS FLOAT) FROM src LIMIT 1;

SELECT CAST(CAST(-3.14 AS DOUBLE) AS FLOAT) FROM src LIMIT 1;
SELECT CAST(CAST(-3.14 AS DECIMAL) AS FLOAT) FROM src LIMIT 1;

SELECT CAST('-38.14' AS FLOAT) FROM src LIMIT 1;

