DESCRIBE FUNCTION tan;
DESCRIBE FUNCTION EXTENDED tan;

SELECT tan(null)
FROM src LIMIT 1;

SELECT tan(1), tan(6), tan(-1.0)
FROM src LIMIT 1;
DESCRIBE FUNCTION tan;
DESCRIBE FUNCTION EXTENDED tan;

SELECT tan(null)
FROM src LIMIT 1;

SELECT tan(1), tan(6), tan(-1.0)
FROM src LIMIT 1;
