explain 
select PI() FROM src LIMIT 1;

select PI() FROM src LIMIT 1;

DESCRIBE FUNCTION PI;
DESCRIBE FUNCTION EXTENDED PI;
explain 
select PI() FROM src LIMIT 1;

select PI() FROM src LIMIT 1;

DESCRIBE FUNCTION PI;
DESCRIBE FUNCTION EXTENDED PI;