CREATE TABLE TEST2a(A INT, B DOUBLE) STORED AS TEXTFILE;
DESCRIBE TEST2a;
DESC TEST2a;
CREATE TABLE TEST2b(A ARRAY<INT>, B DOUBLE, C MAP<DOUBLE, INT>) STORED AS TEXTFILE;
DESCRIBE TEST2b;
SHOW TABLES;
DROP TABLE TEST2a;
SHOW TABLES;
DROP TABLE TEST2b;

EXPLAIN
SHOW TABLES;
