DESCRIBE FUNCTION variance;
DESCRIBE FUNCTION EXTENDED variance;

DESCRIBE FUNCTION var_pop;
DESCRIBE FUNCTION EXTENDED var_pop;
DESCRIBE FUNCTION variance;
DESCRIBE FUNCTION EXTENDED variance;

DESCRIBE FUNCTION var_pop;
DESCRIBE FUNCTION EXTENDED var_pop;
