-- Conversion of main primitive types to Double type: 
SELECT CAST(NULL AS DOUBLE) FROM src LIMIT 1;

SELECT CAST(TRUE AS DOUBLE) FROM src LIMIT 1;

SELECT CAST(CAST(-7 AS TINYINT) AS DOUBLE) FROM src LIMIT 1;
SELECT CAST(CAST(-18 AS SMALLINT) AS DOUBLE) FROM src LIMIT 1;
SELECT CAST(-129 AS DOUBLE) FROM src LIMIT 1;
SELECT CAST(CAST(-1025 AS BIGINT) AS DOUBLE) FROM src LIMIT 1;

SELECT CAST(CAST(-3.14 AS FLOAT) AS DOUBLE) FROM src LIMIT 1;
SELECT CAST(CAST(-3.14 AS DECIMAL) AS DOUBLE) FROM src LIMIT 1;

SELECT CAST('-38.14' AS DOUBLE) FROM src LIMIT 1;

