#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
set -euo pipefail

if [[ "${ASSUME_YES_TO_ALL_QUESTIONS:=false}" == "true" ]]; then
    exit 0
fi

if [[ "${ASSUME_NO_TO_ALL_QUESTIONS:=false}" == "true" ]]; then
    exit 1
fi

if [[ "${ASSUME_QUIT_TO_ALL_QUESTIONS:=false}" == "true" ]]; then
    exit 2
fi


read -r -p "${1}. Are you sure? [y/N/q] " response
case "$response" in
    [yY][eE][sS]|[yY])
        exit 0
        ;;
    [qQ][uU][iI|[tT]|[qQ])
        exit 2
        ;;
    *)
        exit 1
        ;;
esac
