#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
set -euo pipefail

if [[ "${FORCE_ANSWER_TO_QUESTIONS:=""}" != "" ]]; then
    RESPONSE=${FORCE_ANSWER_TO_QUESTIONS}
    echo
    echo "Forcing response '${FORCE_ANSWER_TO_QUESTIONS}' to '${1}?'"
    case "${RESPONSE}" in
        [yY][eE][sS]|[yY])
            exit 0 ;;
        [qQ][uU][iI][tT]|[qQ])
            exit 2 ;;
        *)
            exit 1 ;;
    esac
else
    echo
    echo "Please confirm ${1} images. Are you sure? [y/N/q]"
    read -r RESPONSE
fi

case "${RESPONSE}" in
    [yY][eE][sS]|[yY])
        echo "The answer is 'yes'. Attempting to ${1} images. This can take some time !"
        exit 0
        ;;
    [qQ][uU][iI][tT]|[qQ])
        echo "The answer is 'quit'. Quitting now!"
        exit 2
        ;;
    *)
        echo "The answer is 'no'. Skipping attempt to ${1} images."
        exit 1
        ;;
esac
