#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

echo "=================================="
echo "Free up disk space on CI system"
echo "=================================="

echo "Listing top 100 largest packages (from large to small)"
printf "Installed-Size\tPackage\n"
dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n -r | head -n 100
df -h

echo "Removing large packages"
rm -rf /__t/CodeQL
rm -rf /__t/go
rm -rf /__t/node

apt-get remove --purge -y '^aspnet.*'
apt-get remove --purge -y '^dotnet-.*'
apt-get remove --purge -y '^llvm-.*'
apt-get remove --purge -y 'php.*'
apt-get remove --purge -y '^mongodb-.*'
apt-get remove --purge -y snapd google-chrome-stable microsoft-edge-stable firefox
apt-get remove --purge -y azure-cli google-cloud-sdk mono-devel powershell libgl1-mesa-dri
apt-get autoremove --purge -y
apt-get clean

df -h
