#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -ex

echo "=================================="
echo "Free up disk space on CI system"
echo "=================================="

echo "Listing top 100 largest packages (from large to small)"
printf "Installed-Size\tPackage\n"
dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n -r | head -n 100
df -h

echo "Removing large packages"
sudo rm -rf /usr/share/dotnet/
sudo rm -rf /usr/share/php/
sudo rm -rf /usr/local/graalvm/
sudo rm -rf /usr/local/.ghcup/
sudo rm -rf /usr/local/share/powershell
sudo rm -rf /usr/local/share/chromium
sudo rm -rf /usr/local/lib/android
sudo rm -rf /usr/local/lib/node_modules

sudo rm -rf /opt/az
sudo rm -rf /opt/hostedtoolcache/CodeQL
sudo rm -rf /opt/hostedtoolcache/go
sudo rm -rf /opt/hostedtoolcache/node
du -sh /opt/*

package_patterns=(
  '^aspnet.*'
  '^dotnet-.*'
  '^llvm-.*'
  '^mongodb-.*'
  '^temurin-.*'
  'php.*'
  azure-cli
  firefox
  google-chrome-stable
  google-cloud-sdk
  libgl1-mesa-dri
  microsoft-edge-stable
  mono-devel
  powershell
  snapd
)
for package_pattern in "${package_patterns[@]}"; do
  sudo apt-get remove --purge -y "$package_pattern" || true
done
sudo apt-get autoremove --purge -y
sudo apt-get clean

df -h
