#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -o pipefail

SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
SPARK_ROOT_DIR="$(dirname $SCRIPT_DIR)"

if ! type "shellcheck" > /dev/null; then
  echo "ERROR: You should install shellcheck"
  exit 1
fi

pushd "$SPARK_ROOT_DIR" &> /dev/null

SHELL_SOURCE="$(git ls-files '*.sh' '*.bash')"
echo ${SHELL_SOURCE[*]} | xargs shellcheck -S error;
lint_status=$?

if [ "$lint_status" = "0" ] ; then
   echo "lint-shell checks passed."
else
  echo "lint-shell checks failed."
fi

popd &> /dev/null
exit "$lint_status"
