#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Currently, error prone can only be hooked into `compile` and `test-compile`
# goals in Maven's lifecycle, therefore, we need to run at least `mvn test-compile`
# to ensure it checks both src/main/java and src/test/java

echo -e "q\n" | build/mvn -Pkinesis-asl -Pep-tests -DskipTests \
 clean test-compile 1> /dev/null 2> errorprone.txt

COMPILER_OUTPUT=$(cat errorprone.txt | sed '/^Note/ d')

# Clean up
rm errorprone.txt
build/mvn clean > /dev/null 2>&1

if [[ $COMPILER_OUTPUT =~ "error" ]]; then
    echo -e "Error prone checks failed at following occurrences:\n$COMPILER_OUTPUT"
    exit 1
else
    echo -e "Error prone checks passed."
fi
