#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -o pipefail

SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
SPARK_ROOT_DIR="$(dirname $SCRIPT_DIR)"

if ! type "shellcheck" > /dev/null; then
  echo "ERROR: You should install shellcheck"
  exit 1
fi

if ! type "shfmt" > /dev/null; then
  echo "ERROR: You should install shfmt"
  exit 1
fi

pushd "$SPARK_ROOT_DIR" &> /dev/null

SHELL_SOURCE="$(shfmt -f $SPARK_ROOT_DIR)"

# https://github.com/koalaman/shellcheck/wiki
echo ${SHELL_SOURCE[*]} | xargs shellcheck -S error;
code_style_check_status=$?

# https://github.com/mvdan/sh/blob/master/cmd/shfmt/shfmt.1.scd
# -i 2 Indent with 2 spaces
# -sr Redirect operators will be followed by a space.
# -bn Binary ops like && and | may start a line.
echo ${SHELL_SOURCE[*]} | xargs shfmt -d -i 2 -sr -bn;
indentition_check_status=$?

popd &> /dev/null

if [ "$code_style_check_status" = "0" ] && [ "$indentition_check_status" = "0" ]; then
   echo "lint-shell checks passed."
   exit 0
else
  echo "lint-shell checks failed."
  exit 1
fi
