#!/usr/bin/env bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The current directory of the script.
PYTHON_EXECUTABLE="${PYTHON_EXECUTABLE:-python3}"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
FWDIR="$( cd "$DIR"/.. && pwd )"
cd "$FWDIR"

RUFF_BUILD="${PYTHON_EXECUTABLE} -m ruff"
RUFF_VERSION="0.14.8"
$PYTHON_EXECUTABLE -c 'import ruff' 2> /dev/null
if [ $? -ne 0 ]; then
    echo "The Python library providing the 'ruff' module was not found. Please install Ruff, for example, via 'pip install ruff==$RUFF_VERSION'."
    exit 1
fi

$RUFF_BUILD format python/pyspark dev python/packaging python/benchmarks
