#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Stop on error
set -e
set -x

FWDIR="$(cd "`dirname $0`"/..; pwd)"
cd "$FWDIR"
# Some systems don't have pip or virtualenv - in those cases our tests won't work.
if ! hash virtualenv 2>/dev/null; then
  echo "Missing virtualenv skipping pip installability tests."
  exit 0
fi
if ! hash pip 2>/dev/null; then
  echo "Missing pip, skipping pip installability tests."
  exit 0
fi

if [ -d ~/.cache/pip/wheels/ ]; then
  echo "Cleaning up pip wheel cache so we install the fresh package"
  rm -rf ~/.cache/pip/wheels/
fi

# Create a temp directory for us to work in and save its name to a file for cleanup
echo "Constucting virtual env for testing"
mktemp -d > ./virtual_env_temp_dir
VIRTUALENV_BASE=`cat ./virtual_env_temp_dir`
echo "Using $VIRTUALENV_BASE for virtualenv"
virtualenv $VIRTUALENV_BASE
source $VIRTUALENV_BASE/bin/activate

echo "Creating pip installable source dist"
cd python
python setup.py sdist

echo "Installing dist into virtual env"
cd dist
pip install --upgrade --force-reinstall *.tar.gz

echo "Run basic sanity check on pip installed version with spark-submit"
spark-submit $FWDIR/dev/pip-sanity-check.py
echo "Run basic sanity check with import based"
python $FWDIR/dev/pip-sanity-check.py

cd "$FWDIR"
