#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Stop on error
set -e
set -x

# Create a temp directory for us to work in and save its name to a file for cleanup
echo "Constucting virtual env for testing"
mktemp -d > ./virtual_env_temp_dir
virtualenv `cat ./virtual_env_temp_dir`

echo "Creating pip installable source dist"
cd python
python setup.py sdist

echo "Installing dist into virtual env"
cd dist
pip install *.tar.gz

cd "$FWDIR"
