-- This file is automatically generated by LogicalPlanToSQLSuite.
SELECT id FROM parquet_parquet_t0
--------------------------------------------------------------------------------
SELECT parquet_parquet_t0.`id` FROM parquet_parquet_t0
