-- This file is automatically generated by LogicalPlanToSQLSuite.
SELECT id FROM t0 WHERE id NOT IN (1, 2, 3)
--------------------------------------------------------------------------------
SELECT t0.`id` FROM `default`.`t0` WHERE (NOT (CAST(t0.`id` AS BIGINT) IN (CAST(1 AS BIGINT), CAST(2 AS BIGINT), CAST(3 AS BIGINT))))
