-- This file is automatically generated by LogicalPlanToSQLSuite.
SELECT count(*) as cnt, key%5, grouping_id() FROM parquet_t1 GROUP BY key % 5 WITH CUBE
--------------------------------------------------------------------------------
SELECT count(1) AS `cnt`, (parquet_t1.`key` % CAST(5 AS BIGINT)) AS `(key % CAST(5 AS BIGINT))`, grouping_id() AS `grouping_id()` FROM (SELECT parquet_t1.`key`, parquet_t1.`value`, (parquet_t1.`key` % CAST(5 AS BIGINT)) AS `(key % cast(5 as bigint))` FROM parquet_t1) GROUP BY (parquet_t1.`key` % CAST(5 AS BIGINT)) GROUPING SETS(((parquet_t1.`key` % CAST(5 AS BIGINT))), ())
