-- This file is automatically generated by LogicalPlanToSQLSuite.
select b.key, min(b.value)
from src b
group by b.key
having b.key in (select a.key
                 from src a
                 where a.value > 'val_9' and a.value = min(b.value))
order by b.key
--------------------------------------------------------------------------------
SELECT b.`key`, `min(value)` FROM (SELECT b.`key`, min(b.`value`) AS `min(value)`, min(b.`value`) AS `min(value)` FROM (`default`.`src`) AS b GROUP BY b.`key` HAVING struct(b.`key`, `min(value)`) IN (SELECT a.`key`, a.`value` FROM (`default`.`src`) AS a WHERE (a.`value` > 'val_9'))) ORDER BY b.`key` ASC
