name: Bug Report
description: Submit a bug report for spark
labels: ["Type: Bug"]
body:
  - type: textarea
    attributes:
      label: "Bug description:"
      description: >
        Give a clear description of the bug. Provide some example code, the expected behavior and
        the actual behavior (full error message if applicable). Give as much information about the
        environment as possible (OS, Python version, Java version, Spark version, etc.).
      validations:
        required: true
  - type: dropdown
    attributes:
      label: "Spark version"
      multiple: true
      options:
        - "4.2.0"
        - "4.1.1"
        - "4.1.0"
        - "4.0.2"
        - "4.0.1"
        - "4.0.0"
        - "3.5.8"
        - "3.5.7"
        - "3.5.6"
        - "3.5.5"
        - "3.5.4"
        - "3.5.3"
        - "3.5.2"
        - "3.5.1"
        - "3.5.0"
  - type: dropdown
    attributes:
      label: "Select the relevant components"
      multiple: true
      options:
        - "Block Manager"
        - "Build"
        - "Connect"
        - "Declarative Pipelines"
        - "Deploy"
        - "Documentation"
        - "DStreams"
        - "EC2"
        - "Examples"
        - "Graph"
        - "GraphX"
        - "Input/Output"
        - "Java API"
        - "Kubernetes"
        - "ML"
        - "MLlib"
        - "Optimizer"
        - "Pandas API on Spark"
        - "Project Infra"
        - "PySpark"
        - "Scheduler"
        - "Security"
        - "Shuffle"
        - "Spark Core"
        - "Spark Docker"
        - "Spark Shell"
        - "Spark Submit"
        - "SparkR"
        - "SQL"
        - "Structured Streaming"
        - "Tests"
        - "Web UI"
        - "Windows"
        - "YARN"
