name: Improvement
description: Submit an improvement proposal for spark
labels: ["Type: Improvement"]
body:
  - type: textarea
    attributes:
      label: "Improvement description:"
      description: >
        Describe the improvement you would like to see in Spark in detail. What is the use case?
        How would it benefit the community? What could be the potential risks?
      validations:
        required: true
  - type: dropdown
    attributes:
      label: "Select the relevant components"
      multiple: true
      options:
        - "Block Manager"
        - "Build"
        - "Connect"
        - "Declarative Pipelines"
        - "Deploy"
        - "Documentation"
        - "DStreams"
        - "EC2"
        - "Examples"
        - "Graph"
        - "GraphX"
        - "Input/Output"
        - "Java API"
        - "Kubernetes"
        - "ML"
        - "MLlib"
        - "Optimizer"
        - "Pandas API on Spark"
        - "Project Infra"
        - "PySpark"
        - "Scheduler"
        - "Security"
        - "Shuffle"
        - "Spark Core"
        - "Spark Docker"
        - "Spark Shell"
        - "Spark Submit"
        - "SparkR"
        - "SQL"
        - "Structured Streaming"
        - "Tests"
        - "Web UI"
        - "Windows"
        - "YARN"
