#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2.2"
services:
  mysql:
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d

  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  mongo:
    image: mongo:3
    restart: always

  cassandra:
    image: cassandra:3.0
    restart: always

  rabbitmq:
    image: rabbitmq:3.7
    restart: always

  redis:
    image: redis:5.0.1
    restart: always

  openldap:
    image: osixia/openldap:1.2.0
    restart: always
    command: --copy-service
    environment:
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=insecure
      - LDAP_CONFIG_PASSWORD=insecure
    volumes:
      - ./openldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom

  krb5-kdc-server:
    image: godatadriven/krb5-kdc-server
    hostname: krb5-kdc-server
    domainname: example.com

  airflow-testing:
    image: airflowci/incubator-airflow-ci:latest
    init: true
    environment:
      - USER=airflow
      - ADDITIONAL_PATH=~/.local/bin
      - TOX_ENV
      - PYTHON_VERSION
      - CI
      - TRAVIS
      - TRAVIS_BRANCH
      - TRAVIS_BUILD_DIR
      - TRAVIS_JOB_ID
      - TRAVIS_JOB_NUMBER
      - TRAVIS_PULL_REQUEST
      - TRAVIS_COMMIT
      - TRAVIS_REPO_SLUG
      - TRAVIS_OS_NAME
      - TRAVIS_TAG
    depends_on:
      - postgres
      - mysql
      - mongo
      - cassandra
      - rabbitmq
      - redis
      - openldap
      - krb5-kdc-server
    volumes:
      - ../../:/app
      - ~/.cache/pip:/home/airflow/.cache/pip
      - ~/.wheelhouse/:/home/airflow/.wheelhouse/
    working_dir: /app
