/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.bidfp.binary128;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;
import org.junit.jupiter.api.Test;

/** Intel soft-QUAD oracle checks for the exponential and hyperbolic families. */
final class DpmlExpHyperOracleTest {
  // These vectors are generated by the same Intel soft-QUAD UX entry points.
  private static final int MAX_ULP = 0;

  @Test
  void matchesIntelQuadUx() throws IOException {
    Map<String, Integer> maxima = new LinkedHashMap<>();
    int checked = 0;
    for (IntelF128Oracle.Case testCase : IntelF128Oracle.load()) {
      if (!isFamily(testCase.op)) {
        continue;
      }
      Binary128 actual = evaluate(testCase);
      if (isSpecial(testCase.x)) {
        assertEquals(testCase.expected, actual, mismatch(testCase, actual));
      } else {
        int ulp = IntelF128Oracle.ulpDistance(testCase.expected, actual);
        assertTrue(ulp <= MAX_ULP, mismatch(testCase, actual) + " ulp=" + ulp);
        maxima.merge(testCase.op, ulp, Integer::max);
      }
      checked++;
    }
    assertEquals(112, checked, "oracle vector count");
    assertEquals(7, maxima.size(), "covered operations");
    System.out.println("Intel QUAD exp/hyper max ULP: " + maxima);
  }

  private static boolean isFamily(String op) {
    return "exp".equals(op) || "expm1".equals(op) || "exp2".equals(op)
        || "exp10".equals(op) || "sinh".equals(op) || "cosh".equals(op)
        || "tanh".equals(op);
  }

  private static boolean isSpecial(Binary128 x) {
    return x.isNaN() || x.isInfinite() || x.isZero();
  }

  private static Binary128 evaluate(IntelF128Oracle.Case testCase) {
    StatusFlags status = new StatusFlags();
    RoundingMode mode = RoundingMode.fromIntel(testCase.rnd);
    switch (testCase.op) {
      case "exp":
        return DpmlExp.exp(testCase.x, mode, status);
      case "expm1":
        return DpmlExp.expm1(testCase.x, mode, status);
      case "exp2":
        return DpmlExp.exp2(testCase.x, mode, status);
      case "exp10":
        return DpmlExp.exp10(testCase.x, mode, status);
      case "sinh":
        return DpmlHyper.sinh(testCase.x, mode, status);
      case "cosh":
        return DpmlHyper.cosh(testCase.x, mode, status);
      case "tanh":
        return DpmlHyper.tanh(testCase.x, mode, status);
      default:
        throw new IllegalArgumentException(testCase.op);
    }
  }

  private static String mismatch(IntelF128Oracle.Case testCase, Binary128 actual) {
    return testCase.op + " x=" + testCase.x + " expected=" + testCase.expected
        + " actual=" + actual;
  }
}
