#!/usr/bin/env bash

set -x
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONFIG_PATH=$DIR/../conf/conf.cloudera.yarn

rm -rf $CONFIG_PATH
mkdir $CONFIG_PATH
curl -o /tmp/cloudera_configs.zip http://util-ng.chi.shopify.com:7180/cmf/services/47/client-config
unzip -j /tmp/cloudera_configs.zip -d $CONFIG_PATH

# We need to replace some properties that are only needed by the cluster
sed -i '' -e 's/\/etc\/hadoop.*</Data Rocks!</g' $CONFIG_PATH/core-site.xml
