#!/usr/bin/env bash

set -x
set -e

FWDIR="$(cd `dirname $0`/..; pwd)"
export SPARK_HADOOP_VERSION="$(cat $FWDIR/SHOPIFY_HADOOP_VERSION)"
export SBT_OPTS="-XX:MaxPermSize=2048M"
$FWDIR/sbt/sbt ~assembly
