DECLARE a = "aa";

SELECT 'a', a;
SELECT 'a' AS a, a;

SELECT 'a', a FROM VALUES(1) AS t(a);
SELECT 'a' AS a, a FROM VALUES(1) AS t(a);

SELECT col1 FROM VALUES(1) WHERE EXISTS (SELECT 'col1', col1);
SELECT col1 FROM VALUES(1) WHERE EXISTS (SELECT col1 AS col1, col1);
SELECT col1 FROM VALUES(1) WHERE EXISTS (SELECT 'col1' AS col1, col1);

SELECT col1 FROM VALUES(1) WHERE EXISTS (SELECT 'col1', col1 FROM VALUES(1));
SELECT col1 FROM VALUES(1) WHERE EXISTS (SELECT col1 AS col1, col1 FROM VALUES(1));
SELECT col1 FROM VALUES(1) WHERE EXISTS (SELECT 'col1' AS col1, col1 FROM VALUES(1));

SELECT col1 FROM VALUES(1) GROUP BY col1 HAVING EXISTS (SELECT 'col1', col1);
SELECT col1 FROM VALUES(1) GROUP BY col1 HAVING EXISTS (SELECT col1 AS col1, col1);
SELECT col1 FROM VALUES(1) GROUP BY col1 HAVING EXISTS (SELECT 'col1' AS col1, col1);

SELECT col1 FROM VALUES(1) GROUP BY col1 HAVING EXISTS (SELECT 'col1', col1 FROM VALUES(1));
SELECT col1 FROM VALUES(1) GROUP BY col1 HAVING EXISTS (SELECT col1 AS col1, col1 FROM VALUES(1));
SELECT col1 FROM VALUES(1) GROUP BY col1 HAVING EXISTS (SELECT 'col1' AS col1, col1 FROM VALUES(1));
