-- Tests for DISTINCT with VARIANT and MAP data types

-- Distinct should fail when on VARIANT or MAP data types
SELECT DISTINCT CAST(123.456 AS VARIANT);
SELECT DISTINCT MAP('red', 1, 'green', 2);
SELECT CAST(123.456 AS VARIANT) UNION DISTINCT SELECT CAST(234.567 AS VARIANT);
SELECT MAP('red', 1, 'green', 2) UNION DISTINCT SELECT MAP('blue', 3, 'yellow', 4);
SELECT CAST(123.456 AS VARIANT) EXCEPT DISTINCT SELECT CAST(234.567 AS VARIANT);
SELECT MAP('red', 1, 'green', 2) EXCEPT DISTINCT SELECT MAP('blue', 3, 'yellow', 4);
SELECT CAST(123.456 AS VARIANT) INTERSECT DISTINCT SELECT CAST(234.567 AS VARIANT);
SELECT MAP('red', 1, 'green', 2) INTERSECT DISTINCT SELECT MAP('blue', 3, 'yellow', 4);
