package catalyst
package shark2

import java.io._

import util._

/**
 * Runs the test cases that are included in the hive distribution.
 */
class HiveCompatability extends HiveQueryFileTest {
  /** A list of tests deemed out of scope and thus completely disregarded */
  override def blackList = Seq(
    "hook_order", // These tests use hooks that are not on the classpath and thus break all subsequent SQL execution.
    "hook_context",
    "mapjoin_hook",
    "multi_sahooks",
    "overridden_confs",
    "query_properties",
    "sample10",
    "updateAccessTime",
    "index_compact_binary_search",

    // Hive seems to think 1.0 > NaN = true && 1.0 < NaN = false... which is wrong.
    // http://stackoverflow.com/a/1573715
    "ops_comparison",

    // The skewjoin test seems to never complete on hive...
    "skewjoin",

    // These tests fail and and exit the JVM.
    "auto_join18_multi_distinct",
    "join18_multi_distinct",

    // Uses a serde that isn't on the classpath... breaks other tests.
    "bucketizedhiveinputformat",

    // Avro tests seem to change the output format permanently thus breaking the answer cache, until
    // we figure out what this is the case let just ignore all of them
    ".*avro.*",

    // Unique joins are weird and will require a lot of hacks (see comments in hive parser)
    "uniquejoin",

    // Hive seems to get the wrong answer on some outer joins.  MySQL agrees with catalyst.
    "auto_join29"
  )

  /**
   * The set of tests that are believed to be working in catalyst. Tests not in whiteList
   * blacklist are implicitly marked as ignored.
   */
  override def whiteList = Seq(
    "add_part_exist",
    "alter2",
    "alter4",
    "alter_partition_format_loc",
    "alter_table_serde",
    "authorization_3",
    "authorization_5",
    "auto_join23",
    "auto_join24",
    "auto_join26",
    "auto_join28",
    "auto_join_nulls",
    "binarysortable_1",
    "bucket1",
    "bucketmapjoin6",
    "bucketmapjoin_negative",
    "bucketmapjoin_negative2",
    "combine1",
    "count",
    "create_default_prop",
    "ct_case_insensitive",
    "database_location",
    "database_properties",
    "default_partition_name",
    "delimiter",
    "describe_database_json",
    "describe_table_json",
    "diff_part_input_formats",
    "disable_file_format_check",
    "drop_function",
    "drop_index",
    "drop_partitions_filter",
    "drop_partitions_filter2",
    "drop_partitions_filter3",
    "drop_table",
    "drop_view",
    "groupby1",
    "groupby1_map",
    "groupby1_map_nomap",
    "groupby1_map_skew",
    "groupby1_noskew",
    "groupby4_map",
    "groupby4_map_skew",
    "groupby5",
    "groupby5_map",
    "groupby5_map_skew",
    "groupby5_noskew",
    "implicit_cast1",
    "index_auth",
    "index_auto_mult_tables",
    "index_auto_mult_tables_compact",
    "index_auto_self_join",
    "index_auto_update",
    "index_stale",
    "innerjoin",
    "inoutdriver",
    "input0",
    "input11",
    "input11_limit",
    "input22",
    "input23",
    "input24",
    "input25",
    "input41",
    "input4_cb_delim",
    "input4_limit",
    "input6",
    "input7",
    "input9",
    "input_part1",
    "inputddl4",
    "inputddl7",
    "inputddl8",
    "insert1",
    "join0",
    "join1",
    "join10",
    "join11",
    "join12",
    "join13",
    "join14",
    "join14_hadoop20",
    "join15",
    "join16",
    "join17",
    "join18",
    "join19",
    "join2",
    "join20",
    "join22",
    "join23",
    "join24",
    "join25",
    "join26",
    "join27",
    "join28",
    "join29",
    "join3",
    "join30",
    "join31",
    "join32",
    "join33",
    "join34",
    "join35",
    "join36",
    "join37",
    "join39",
    "join4",
    "join40",
    "join5",
    "join6",
    "join8",
    "join9",
    "join_casesensitive",
    "join_empty",
    "join_hive_626",
    "join_nulls",
    "join_reorder2",
    "join_reorder3",
    "join_view",
    "keyword_1",
    "lineage1",
    "literal_double",
    "literal_ints",
    "literal_string",
    "louter_join_ppr",
    "mapjoin1",
    "mapjoin_mapjoin",
    "mapjoin_subquery",
    "mapjoin_subquery2",
    "mergejoins",
    "misc_json",
    "no_hooks",
    "noalias_subq1",
    "nomore_ambiguous_table_col",
    "notable_alias1",
    "notable_alias2",
    "nullgroup",
    "nullgroup2",
    "nullgroup3",
    "nullgroup5",
    "nullinput",
    "nullinput2",
    "nullscript",
    "outer_join_ppr",
    "part_inherit_tbl_props",
    "part_inherit_tbl_props_empty",
    "part_inherit_tbl_props_with_star",
    "partitions_json",
    "ppd1",
    "ppd_gby",
    "ppd_gby_join",
    "ppd_join",
    "ppd_join2",
    "ppd_join3",
    "ppd_outer_join1",
    "ppd_outer_join2",
    "ppd_outer_join3",
    "ppd_outer_join4",
    "ppd_outer_join5",
    "ppd_random",
    "ppd_repeated_alias",
    "ppd_udf_col",
    "ppd_union",
    "progress_1",
    "protectmode",
    "protectmode2",
    "query_with_semi",
    "quote2",
    "rename_column",
    "router_join_ppr",
    "select_as_omitted",
    "set_variable_sub",
    "show_describe_func_quotes",
    "show_functions",
    "smb_mapjoin_10",
    "subq2",
    "tablename_with_select",
    "udf2",
    "udf5",
    "udf7",
    "udf9",
    "udf_10_trims",
    "udf_abs",
    "udf_acos",
    "udf_add",
    "udf_ascii",
    "udf_asin",
    "udf_atan",
    "udf_avg",
    "udf_bigint",
    "udf_bin",
    "udf_bitwise_and",
    "udf_bitwise_not",
    "udf_bitwise_or",
    "udf_bitwise_xor",
    "udf_boolean",
    "udf_ceil",
    "udf_ceiling",
    "udf_conv",
    "udf_cos",
    "udf_count",
    "udf_date_add",
    "udf_date_sub",
    "udf_datediff",
    "udf_day",
    "udf_dayofmonth",
    "udf_double",
    "udf_exp",
    "udf_field",
    "udf_float",
    "udf_floor",
    "udf_from_unixtime",
    "udf_greaterthan",
    "udf_greaterthanorequal",
    "udf_hex",
    "udf_hour",
    "udf_index",
    "udf_int",
    "udf_isnotnull",
    "udf_isnull",
    "udf_lcase",
    "udf_length",
    "udf_lessthan",
    "udf_lessthanorequal",
    "udf_ln",
    "udf_log",
    "udf_log10",
    "udf_log2",
    "udf_lower",
    "udf_lpad",
    "udf_ltrim",
    "udf_minute",
    "udf_modulo",
    "udf_month",
    "udf_not",
    "udf_or",
    "udf_parse_url",
    "udf_pmod",
    "udf_positive",
    "udf_pow",
    "udf_power",
    "udf_rand",
    "udf_regexp_extract",
    "udf_regexp_replace",
    "udf_repeat",
    "udf_rlike",
    "udf_round",
    "udf_rpad",
    "udf_rtrim",
    "udf_second",
    "udf_sign",
    "udf_sin",
    "udf_smallint",
    "udf_space",
    "udf_sqrt",
    "udf_std",
    "udf_stddev",
    "udf_stddev_pop",
    "udf_stddev_samp",
    "udf_string",
    "udf_substring",
    "udf_subtract",
    "udf_sum",
    "udf_tan",
    "udf_tinyint",
    "udf_to_date",
    "udf_trim",
    "udf_ucase",
    "udf_unhex",
    "udf_unix_timestamp",
    "udf_upper",
    "udf_var_pop",
    "udf_var_samp",
    "udf_variance",
    "udf_weekofyear",
    "udf_when",
    "udf_xpath",
    "udf_xpath_boolean",
    "udf_xpath_double",
    "udf_xpath_float",
    "udf_xpath_int",
    "udf_xpath_long",
    "udf_xpath_short",
    "union10",
    "union11",
    "union13",
    "union14",
    "union15",
    "union16",
    "union2",
    "union20",
    "union27",
    "union28",
    "union29",
    "union30",
    "union4",
    "union5",
    "union7",
    "union8",
    "union9",
    "union_script"
  )

  // TODO: bundle in jar files... get from classpath
  lazy val hiveQueryDir = new File(TestShark.hiveDevHome, "ql/src/test/queries/clientpositive")
  def testCases = hiveQueryDir.listFiles.map(f => f.getName.stripSuffix(".q") -> f).toMap
}
