DESCRIBE FUNCTION atan;
DESCRIBE FUNCTION EXTENDED atan;

SELECT atan(null)
FROM src LIMIT 1;

SELECT atan(1), atan(6), atan(-1.0)
FROM src LIMIT 1;
DESCRIBE FUNCTION atan;
DESCRIBE FUNCTION EXTENDED atan;

SELECT atan(null)
FROM src LIMIT 1;

SELECT atan(1), atan(6), atan(-1.0)
FROM src LIMIT 1;
