#!/bin/bash

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This file is used for Binder integration to install PySpark available in
# Jupyter notebook.

# This Binder notebook is for releases
# VERSION=$(python -c "exec(open('python/pyspark/version.py').read()); print(__version__)")
# pip install plotly "pyspark[sql,ml,mllib,pandas_on_spark]<=$VERSION"
cd python
cat x* > pyspark-3.2.0.dev0.tar.gz
ls -al
ls -al pyspark-3.2.0.dev0.tar.gz
pip install plotly "pyspark-3.2.0.dev0.tar.gz[sql,ml,mllib,pandas_on_spark]"
