#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: "Branch-4.x CI Scheduler"

on:
  schedule:
    - cron: '0 4 */2 * *'
    - cron: '0 7 */2 * *'
    - cron: '0 11 */2 * *'
    - cron: '0 16 */2 * *'
    - cron: '0 18 */2 * *'
    - cron: '0 19 */2 * *'
    - cron: '0 21 */2 * *'
    - cron: '0 22 */2 * *'
  workflow_dispatch:
    inputs:
      target:
        description: Target workflow to run
        required: true
        type: choice
        default: all
        options:
          - all
          - maven
          - maven_java21
          - java17
          - java21
          - java25
          - non_ansi
          - python_3.11
          - python_3.14

jobs:
  schedule:
    if: github.repository == 'apache/spark'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      actions: write
    steps:
      - name: Maven Build
        if: >-
          github.event.schedule == '0 16 */2 * *' ||
          (github.event_name == 'workflow_dispatch' &&
            (inputs.target == 'maven' || inputs.target == 'all'))
        run: |
          gh workflow run build_maven.yml --repo ${{ github.repository }} --ref branch-4.x
      - name: Maven Java 21 Build
        if: >-
          github.event.schedule == '0 18 */2 * *' ||
          (github.event_name == 'workflow_dispatch' &&
            (inputs.target == 'maven_java21' || inputs.target == 'all'))
        run: |
          gh workflow run build_maven_java21.yml --repo ${{ github.repository }} --ref branch-4.x
      - name: Java 17 Build
        if: >-
          github.event.schedule == '0 11 */2 * *' ||
          (github.event_name == 'workflow_dispatch' &&
            (inputs.target == 'java17' || inputs.target == 'all'))
        run: |
          gh workflow run build_java17.yml --repo ${{ github.repository }} --ref branch-4.x
      - name: Java 21 Build
        if: >-
          github.event.schedule == '0 7 */2 * *' ||
          (github.event_name == 'workflow_dispatch' &&
            (inputs.target == 'java21' || inputs.target == 'all'))
        run: |
          gh workflow run build_java21.yml --repo ${{ github.repository }} --ref branch-4.x
      - name: Java 25 Build
        if: >-
          github.event.schedule == '0 22 */2 * *' ||
          (github.event_name == 'workflow_dispatch' &&
            (inputs.target == 'java25' || inputs.target == 'all'))
        run: |
          gh workflow run build_java25.yml --repo ${{ github.repository }} --ref branch-4.x
      - name: Non-ANSI Build
        if: >-
          github.event.schedule == '0 4 */2 * *' ||
          (github.event_name == 'workflow_dispatch' &&
            (inputs.target == 'non_ansi' || inputs.target == 'all'))
        run: |
          gh workflow run build_non_ansi.yml --repo ${{ github.repository }} --ref branch-4.x
      - name: Python 3.11 Build
        if: >-
          github.event.schedule == '0 19 */2 * *' ||
          (github.event_name == 'workflow_dispatch' &&
            (inputs.target == 'python_3.11' || inputs.target == 'all'))
        run: |
          gh workflow run build_python_3.11.yml --repo ${{ github.repository }} --ref branch-4.x
      - name: Python 3.14 Build
        if: >-
          github.event.schedule == '0 21 */2 * *' ||
          (github.event_name == 'workflow_dispatch' &&
            (inputs.target == 'python_3.14' || inputs.target == 'all'))
        run: |
          gh workflow run build_python_3.14.yml --repo ${{ github.repository }} --ref branch-4.x
