#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: GitHub Pages deployment

on:
  workflow_run:
    workflows: ["Build"]
    branches: [master]
    types: [completed]

concurrency:
  group: 'docs preview'
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Documentation to GitHub Pages
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages # https://github.com/actions/deploy-pages/issues/271
    steps:
      - name: Print triggering commit
        run: |
          echo "Title: ${{ github.event.workflow_run.display_title }}"
          echo "SHA:   ${{ github.event.workflow_run.head_sha }}"
      - name: Download documentation site
        uses: actions/download-artifact@v8
        with:
          name: docs-site-${{ github.event.workflow_run.head_branch }}-${{ github.event.workflow_run.head_sha }}
          path: docs/_site
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/_site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
